language: node_js
node_js:
  - '8'
services:
  - postgresql
env:
  - NODE_ENV=test
before_install:
  - npm i -g npm
before_script:
  - cp .env.travis .env
  - psql -c 'create database intuit_test;' -U postgres
notifications:
  email: false